name: Validate Nix Flake

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty

    - name: Check Flake
      run: nix flake check --accept-flake-config
